### ISSUE TITLE
Not work with woltk dbc files

### ISSUE THREAD

**Issue by Krutok** [Marlamin/DBC2CSV#1]
I wanted to use the tool with my woltk dbc files, but it doesn't work, even though it says DBC files, not just db2 files.
![Screenshot 2023-07-30 170906](https://github.com/Marlamin/DBC2CSV/assets/47283866/ecfdc4aa-ceab-48b8-9c75-bc034af4b5b7)

**Comment by Marlamin** [comment]
Hmm, I'm guessing it isn't able to detect a version for older DBCs like that, I'll add a note for that in the readme as I don't think that'll ever work properly.
