### ISSUE TITLE
I tried to download your file from the link you showed and it says no definition

### ISSUE THREAD

**Issue by trcrsired** [Marlamin/DBC2CSV#3]
D:\Downloads\Release-win-x64>DBC2CSV SoundEntries.db2
Reloading definitions from directory D:\Downloads\Release-win-x64\definitions
Loaded 1153 definitions!
Exporting table SoundEntries
Failed to export DB2 SoundEntries: No definition found for this file.

**Comment by Marlamin** [comment]
From what patch is the DB2?

**Comment by trcrsired** [comment]
the latest one

**Comment by trcrsired** [comment]
[SoundEntries.6.2.4.21676 (PTR) 5f78ecd9306c65706c1c87c3fc9d3652.db2.zip](https://github.com/Marlamin/DBC2CSV/files/13721551/SoundEntries.6.2.4.21676.PTR.5f78ecd9306c65706c1c87c3fc9d3652.db2.zip)

**Comment by Marlamin** [comment]
SoundEntries does not exist in the latest patch

**Comment by trcrsired** [comment]
i am not using the latest patch one. I am trying to extract from old one so i can port the post cataclysm music to classic wow. Just using WoD should be ok.

For some data like legion music in stormwind, i will add that manually.

**Comment by Marlamin** [comment]
The specific patch the DB2 is from has to be listed in https://github.com/wowdev/WoWDBDefs/blob/master/definitions/SoundEntries.dbd otherwise it can't work

**Comment by trcrsired** [comment]
the thing is that none of them works. even mists of pandaria does not work either. do not know why

**Comment by Marlamin** [comment]
6.2.4 is not supported in that DBD, maybe try 6.0.1.18179.

**Comment by trcrsired** [comment]
tried. does not work either

**Comment by trcrsired** [comment]
[SoundEntries.6.0.1.18179 (Beta) 52e10dc4bcd7fb037a210b973bc14f47.dbc.zip](https://github.com/Marlamin/DBC2CSV/files/13721573/SoundEntries.6.0.1.18179.Beta.52e10dc4bcd7fb037a210b973bc14f47.dbc.zip)

**Comment by trcrsired** [comment]
DBC2CSV SoundEntries.dbc
Reloading definitions from directory D:\Downloads\Release-win-x64\definitions
Loaded 1153 definitions!
Exporting table SoundEntries
Failed to export DB2 SoundEntries: No definition found for this file.

**Comment by trcrsired** [comment]
can you have a look at it? Thank you

**Comment by Marlamin** [comment]
Sure, taking a peek

**Comment by Marlamin** [comment]
Oh, yeah, as the README says only 7.0.1+ is supported. SoundEntries was removed before Legion so you won't be able to export this using this tool.

>  Only files versioned WDB5+ (~Legion) and up will work.
